### ISSUE TITLE
Minimum and Maximum values from JSDoc not propagated to UI

### ISSUE THREAD

**Issue by PuneetKohli** [Surnet/swagger-jsdoc#160]
Example 

```
parameters:
  param1:
    name: param1
    description: param1
    in: formData
    required: false
    type: number
    minimum: 0
    maximum: 1
```

The min and max is not shown anywhere in the UI for users to know/see.
