### ISSUE TITLE
Adding multiple anchors seems to work but also prints an error

### ISSUE THREAD

**Issue by keon2567** [Surnet/swagger-jsdoc#252]
**Describe the bug**
It appears that using the anchor multiple times gives me an error but also seems to render an expected ui.

Error:
```
Not all input has been taken into account at your final specification.
Here's the report: 


 YAMLReferenceError: Aliased anchor not found: LZCustomerIdHeader at line 8, column 9:

      - *LZCustomerIdHeader
        ^^^^^^^^^^^^^^^^^^^
```

**To Reproduce**
common.yaml
```
components:
  parameters:
    &CustomerIdHeader
      name: x-customer-id
      in: headers
      required: true
      type: integer
    &OrderStatus
      name: status
      in: query
      schema:
        type: string
        enum: [Pending, InProgress, Complete, Cancelled]
```

api.js
```
/**
 * @swagger
 * /api/v1/example:
 *   get:
 *     summary: this is just an example.
 *     produces: [application/json]
 *     parameters:
 *       - *CustomerIdHeader
 *       - *OrderStatus
 *     responses:
 *       200:
 *         description: all good here.
 */
const example = async (req, res, next) => { ... }
...
```
This seems to work fine, but it prints an error as noted above.

**Expected behavior**
Should not print any error.

** Additional Notes**
I tried adding the same anchor multiple times, but that results the same.
